#!/bin/bash

echo -n 'echo '
echo -n ' -e '
mode=normal

command=$1
if [[ "$command" != 'echo' ]]; then
   exit  
fi

shift
for a in "$@"; do
  if [[ "$a" == '--ns-echo-pretty-names-fg' ]]; then
     mode=foreground
  elif [[ "$mode" == 'foreground' ]]; then
    mode=normal
    case $a in
       'red') echo -ne  "\033[31m";;
       'green') echo -ne "\033[32m";;
      esac
  else
    echo -n " $a "
  fi
done

echo -ne '\033[39m\033[49m'
