#!/bin/bash

echo -n 'echo '
echo -n ' -e '
mode=normal

command=$1
if [[ "$command" != 'echo' ]]; then
   exit  
fi

function set_color {
   case $mode in
     'foreground') term_mode='3';;
     'background') term_mode='4';;
   esac
   case $a in
   'black')echo -ne  "\033[${term_mode}0m";;
   'red') echo -ne  "\033[${term_mode}1m";;
   'green') echo -ne "\033[${term_mode}2m";;
   'orange') echo -ne "\033[${term_mode}3m";;
   'blue') echo -ne "\033[${term_mode}4m";;
   'mangeta') echo -ne "\033[${term_mode}5m";;
   'cyan') echo -ne "\033[${term_mode}6m";;
   'white') echo -ne "\033[${term_mode}7m";;
   esac
}

shown=false

shift
for a in "$@"; do
  if [[ "$a" == '--ns-echo-pretty-names-fg' ]]; then
     mode=foreground
  elif [[ "$a" == '--ns-echo-pretty-names-bg' ]]; then
     mode=background
  elif [[ "$mode" == 'foreground' ]]; then
    set_color
    mode=normal
  elif [[ "$mode" == 'background' ]]; then
    set_color
    mode=normal
  else
   if [[ "$shown" == "true" ]]; then
      echo -n ' '
   fi
    echo -n $a
    shown=true
  fi
done

echo -ne '\033[39m\033[49m'
