#!/bin/bash

echo -n 'echo '
echo -n ' -e '
mode=normal

command=$1
if [[ "$command" != 'echo' ]]; then
   exit  
fi

function set_color {
   case $mode in
     'foreground') term_mode='3';;
     'background') term_mode='4';;
   esac
   case $a in
   'red') echo -ne  "\033[${term_mode}1m";;
   'green') echo -ne "\033[${term_mode}2m";;
   esac
}

shift
for a in "$@"; do
  if [[ "$a" == '--ns-echo-pretty-names-fg' ]]; then
     mode=foreground
  elif [[ "$a" == '--ns-echo-pretty-names-bg' ]]; then
     mode=background
  elif [[ "$mode" == 'foreground' ]]; then
    set_color
    mode=normal
  elif [[ "$mode" == 'background' ]]; then
    set_color
    mode=normal
  else
    echo -n " $a "
  fi
done

echo -ne '\033[39m\033[49m'
